version: "2"

services:
  api-server:
    image: node:8
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/home/node/app
    ports:
      - "5000:3000"
    command: "npm start"
    restart: unless-stopped

